function KKT = KKT_gen(in1,in2)
%KKT_GEN
%    KKT = KKT_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:16:55

ieq_act_1 = in2(1,:);
ieq_act_2 = in2(2,:);
miu_ieq_1 = in1(5,:);
miu_ieq_2 = in1(6,:);
v1 = in1(3,:);
v2 = in1(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
KKT = sparse([1,2,3,4],[1,1,1,1],[v1+conj(v1)-miu_ieq_1.*exp(-conj(v1)),-miu_ieq_1+miu_ieq_2+v2+conj(v2),ieq_act_1.*(v2-exp(-v1)+sin(x1).*(1.7e1./1.0e1))+miu_ieq_1.*(ieq_act_1-1.0),ieq_act_2.*(-v2+cos(x2).*(1.0./5.0)+2.0)+miu_ieq_2.*(ieq_act_2-1.0)],4,1);
