function obj = obj_gen(in1)
%OBJ_GEN
%    OBJ = OBJ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:16:56

v1 = in1(1,:);
v2 = in1(2,:);
obj = v1.*conj(v1)+v2.*conj(v2);
