function out1 = event_gen(in1)
%EVENT_GEN
%    OUT1 = EVENT_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Jul-2019 19:29:19

miu_ieq_1 = in1(4,:);
miu_ieq_2 = in1(5,:);
z = in1(3,:);
out1 = [miu_ieq_1-z-3.0./2.0;miu_ieq_2+z-3.0./2.0];
