function f = f_gen(in1,z)
%F_GEN
%    F = F_GEN(IN1,Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Jul-2019 19:29:19

T = in1(1,:);
f = [1.0;1.0./(exp(T.*-1.0e1+5.0)+exp(T.*1.0e1-5.0)).^2.*-2.0];
