function hieq = hieq_gen(z)
%HIEQ_GEN
%    HIEQ = HIEQ_GEN(Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Jul-2019 19:29:19

hieq = [z+3.0./2.0;-z+3.0./2.0];
