function obj = obj_gen(z)
%OBJ_GEN
%    OBJ = OBJ_GEN(Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Jul-2019 19:29:19

t2 = z.^2;
obj = t2.*(-5.0./2.0)-z.*4.5398e-5+t2.*z.*(1.0./2.0)+t2.^2;
