function out1 = event_gen(in1)
%EVENT_GEN
%    OUT1 = EVENT_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2019 11:17:27

miu_ieq_1 = in1(13,:);
miu_ieq_2 = in1(14,:);
miu_ieq_3 = in1(15,:);
v1 = in1(7,:);
v4 = in1(10,:);
v5 = in1(11,:);
out1 = [miu_ieq_1-v1;miu_ieq_2-v4;miu_ieq_3-v5];
