function f = f_gen(in1,in2)
%F_GEN
%    F = F_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2019 11:17:28

cx = in1(1,:);
v5 = in2(7,:);
v6 = in2(8,:);
vupt1 = in2(1,:);
vupt2 = in2(2,:);
f = [cx.*v5;-cx.*vupt1;-cx.*vupt2;cx.*v6];
