function heq = heq_gen(in1)
%HEQ_GEN
%    HEQ = HEQ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2019 11:17:28

v1 = in1(3,:);
v2 = in1(4,:);
v3 = in1(5,:);
v4 = in1(6,:);
v5 = in1(7,:);
v6 = in1(8,:);
vupt1 = in1(1,:);
vupt2 = in1(2,:);
heq = [-v1-v4+vupt1;v1-v2+vupt2;v2-v3;-v1+v3+v4-v5;v2+v3-v6;vupt1-7.6e1./2.1e1;vupt2-1.0];
