function hieq = hieq_gen(in1)
%HIEQ_GEN
%    HIEQ = HIEQ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2019 11:17:30

v1 = in1(7,:);
v4 = in1(10,:);
v5 = in1(11,:);
hieq = [v1;v4;v5];
