function obj = obj_gen(in1)
%OBJ_GEN
%    OBJ = OBJ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2019 11:17:28

v1 = in1(3,:);
v2 = in1(4,:);
v3 = in1(5,:);
v4 = in1(6,:);
v5 = in1(7,:);
v6 = in1(8,:);
vupt1 = in1(1,:);
vupt2 = in1(2,:);
obj = sqrt(v1.*conj(v1)+v2.*conj(v2)+v3.*conj(v3)+v4.*conj(v4)+v5.*conj(v5)+v6.*conj(v6)+vupt1.*conj(vupt1)+vupt2.*conj(vupt2));
