function out1 = event_gen(in1)
%EVENT_GEN
%    OUT1 = EVENT_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:17:59

miu_ieq_1 = in1(5,:);
miu_ieq_2 = in1(6,:);
x1 = in1(1,:);
x2 = in1(2,:);
z1 = in1(3,:);
z2 = in1(4,:);
out1 = [miu_ieq_1-z2+exp(-z1)-sin(x1).*(9.0./5.0);miu_ieq_2+z2-cos(x2).*(1.0./5.0)-2.0];
