function f = f_gen(in1,in2)
%F_GEN
%    F = F_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:17:59

x1 = in1(1,:);
z1 = in2(1,:);
z2 = in2(2,:);
f = [sin(z1.*z2)+1.0;cos(z2+x1.*z1)];
