function hieq = hieq_gen(in1)
%HIEQ_GEN
%    HIEQ = HIEQ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:18:06

x1 = in1(1,:);
x2 = in1(2,:);
z1 = in1(3,:);
z2 = in1(4,:);
hieq = [z2-exp(-z1)+sin(x1).*(9.0./5.0);-z2+cos(x2).*(1.0./5.0)+2.0];
