function KKT = KKT_gen(in1,in2)
%KKT_GEN
%    KKT = KKT_GEN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:17:59

ieq_act_1 = in2(1,:);
ieq_act_2 = in2(2,:);
miu_ieq_1 = in1(5,:);
miu_ieq_2 = in1(6,:);
x1 = in1(1,:);
x2 = in1(2,:);
z1 = in1(3,:);
z2 = in1(4,:);
KKT = sparse([1,2,3,4],[1,1,1,1],[z1+conj(z1)-miu_ieq_1.*exp(-conj(z1)),-miu_ieq_1+miu_ieq_2+z2+conj(z2),ieq_act_1.*(z2-exp(-z1)+sin(x1).*(9.0./5.0))+miu_ieq_1.*(ieq_act_1-1.0),ieq_act_2.*(-z2+cos(x2).*(1.0./5.0)+2.0)+miu_ieq_2.*(ieq_act_2-1.0)],4,1);
