function obj = obj_gen(in1)
%OBJ_GEN
%    OBJ = OBJ_GEN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    14-Jul-2020 00:17:59

z1 = in1(1,:);
z2 = in1(2,:);
obj = z1.*conj(z1)+z2.*conj(z2);
